#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define NRF_MPU_LIB_ENABLED 0
#define NRF_STACK_GUARD_ENABLED 0
#define NRF_STACK_GUARD_CONFIG_SIZE 7
#define NRF_LOG_STR_FORMATTER_TIMESTAMP_FORMAT_ENABLED 0
 
// nRF_Drivers 

// GPIOTE
#define GPIOTE_ENABLED 1
#define GPIOTE_CONFIG_IRQ_PRIORITY 6

// <e> NRFX_GPIOTE
#define NRFX_GPIOTE_ENABLED 1
#define NRFX_GPIOTE_CONFIG_IRQ_PRIORITY 6
#define NRFX_GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 1

// <e> NRF_CLOCK
#define NRF_CLOCK_ENABLED 1
#define CLOCK_CONFIG_LF_SRC 1
#define CLOCK_CONFIG_IRQ_PRIORITY 6

// NRFX_CLOCK
#define NRFX_CLOCK_ENABLED 1
#define NRFX_CLOCK_CONFIG_LF_SRC 1
#define NRFX_CLOCK_CONFIG_IRQ_PRIORITY 6


// PWM
#define PWM_ENABLED 1

// NRFX_PWM
#define NRFX_PWM_ENABLED 1
#define NRFX_PWM0_ENABLED 1
#define NRFX_PWM1_ENABLED 0
#define NRFX_PWM2_ENABLED 0
#define NRFX_PWM3_ENABLED 0
#define NRFX_PWM_DEFAULT_CONFIG_OUT0_PIN 31
#define NRFX_PWM_DEFAULT_CONFIG_OUT1_PIN 31
#define NRFX_PWM_DEFAULT_CONFIG_OUT2_PIN 31
#define NRFX_PWM_DEFAULT_CONFIG_OUT3_PIN 31
#define NRFX_PWM_DEFAULT_CONFIG_BASE_CLOCK 4
#define NRFX_PWM_DEFAULT_CONFIG_TOP_VALUE 1000
#define NRFX_PWM_DEFAULT_CONFIG_IRQ_PRIORITY 6

// NRFX_RTC
#define NRFX_RTC_ENABLED 1
#define NRFX_RTC0_ENABLED 1
#define NRFX_RTC1_ENABLED 1
#define NRFX_RTC2_ENABLED 1
#define NRFX_RTC_MAXIMUM_LATENCY_US 2000
#define NRFX_RTC_DEFAULT_CONFIG_FREQUENCY 32768
#define NRFX_RTC_DEFAULT_CONFIG_RELIABLE 0
#define NRFX_RTC_DEFAULT_CONFIG_IRQ_PRIORITY 6
#define NRFX_RTC_CONFIG_LOG_ENABLED 0
#define NRFX_RTC_CONFIG_LOG_LEVEL 3
#define NRFX_RTC_CONFIG_INFO_COLOR 0
#define NRFX_RTC_CONFIG_DEBUG_COLOR 0


// SYSTICK
#define SYSTICK_ENABLED 1

// NRFX_SYSTICK
#define NRFX_SYSTICK_ENABLED 1


// POWER
#define POWER_ENABLED 1
#define POWER_CONFIG_IRQ_PRIORITY 6

//nRF_Libraries 
#define APP_FIFO_ENABLED 1
#define APP_GPIOTE_ENABLED 0
#define APP_PWM_ENABLED 0
#define APP_TIMER_ENABLED 1
#define APP_TIMER_CONFIG_RTC_FREQUENCY 1
#define APP_TIMER_CONFIG_IRQ_PRIORITY 6
#define APP_TIMER_KEEPS_RTC_ACTIVE 0
#define APP_TIMER_SAFE_WINDOW_MS 300000
#define APP_TIMER_CONFIG_OP_QUEUE_SIZE 10
#define APP_USBD_CONFIG_LOG_ENABLED 0

// NRFX_NVMC
#define NRFX_NVMC_ENABLED 1

// <e> RTC_ENABLED - nrf_drv_rtc - RTC peripheral driver - legacy layer
//==========================================================
#ifndef RTC_ENABLED
#define RTC_ENABLED 0
#endif
// <o> RTC_DEFAULT_CONFIG_FREQUENCY - Frequency  <16-32768> 


#ifndef RTC_DEFAULT_CONFIG_FREQUENCY
#define RTC_DEFAULT_CONFIG_FREQUENCY 32768
#endif

// <q> RTC_DEFAULT_CONFIG_RELIABLE  - Ensures safe compare event triggering
 

#ifndef RTC_DEFAULT_CONFIG_RELIABLE
#define RTC_DEFAULT_CONFIG_RELIABLE 0
#endif

// <o> RTC_DEFAULT_CONFIG_IRQ_PRIORITY  - Interrupt priority
 

// <i> Priorities 0,2 (nRF51) and 0,1,4,5 (nRF52) are reserved for SoftDevice
// <0=> 0 (highest) 
// <1=> 1 
// <2=> 2 
// <3=> 3 
// <4=> 4 
// <5=> 5 
// <6=> 6 
// <7=> 7 

#ifndef RTC_DEFAULT_CONFIG_IRQ_PRIORITY
#define RTC_DEFAULT_CONFIG_IRQ_PRIORITY 6
#endif

// <q> RTC0_ENABLED  - Enable RTC0 instance
 

#ifndef RTC0_ENABLED
#define RTC0_ENABLED 1
#endif

// <q> RTC1_ENABLED  - Enable RTC1 instance
 

#ifndef RTC1_ENABLED
#define RTC1_ENABLED 0
#endif

// <q> RTC2_ENABLED  - Enable RTC2 instance
 

#ifndef RTC2_ENABLED
#define RTC2_ENABLED 0
#endif

// <o> NRF_MAXIMUM_LATENCY_US - Maximum possible time[us] in highest priority interrupt 
#ifndef NRF_MAXIMUM_LATENCY_US
#define NRF_MAXIMUM_LATENCY_US 2000
#endif

 
#endif //APP_CONFIG_H
